---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sentry.sentry.io
  resources:
  - sentryclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.sentry.io
  resources:
  - sentryclusters/finalizers
  verbs:
  - update
- apiGroups:
  - sentry.sentry.io
  resources:
  - sentryclusters/status
  verbs:
  - get
  - patch
  - update
