apiVersion: v1
data:
  admin-password: MTIzNDU=
  sentry-django-secret: >-
    c2VudHJ5LWRqYW5nby1zZWNyZXRzZW50cnktZGphbmdvLXNlY3JldHNlbnRyeS1kamFuZ28tc2VjcmV0
kind: Secret
metadata:
  name: sentry-secret
type: Opaque
